apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keptn-ortelius-service.serviceAccountName" . }}
  labels:
    {{- include "keptn-ortelius-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-{{ .Release.Namespace }}-keptn-ortelius-service-cluster-admin
  labels:
    {{- include "keptn-ortelius-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "keptn-ortelius-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
